
create table if not exists public.diagnostico_submissions (
  id bigint generated always as identity primary key,
  submission_id uuid not null default gen_random_uuid() unique,
  nombre_completo text not null,
  pais_origen text not null,
  nacionalidad text not null,
  edad text not null,
  estado_civil text not null,
  viaja_solo text not null,
  tiene_hijos text not null,
  viaja_mascota text not null,
  ciudad_preferida text,
  bundesland_preferido text,
  tiene_contactos_alemania text not null,
  donde_contactos text,
  universidad text not null,
  anio_graduacion text not null,
  realizo_internado text not null,
  tiene_especialidad text not null,
  cual_especialidad text,
  anios_experiencia text not null,
  areas_trabajo text not null,
  nivel_aleman text not null,
  tiene_certificado text not null,
  cual_certificado text,
  estudia_actualmente text not null,
  horas_por_semana text,
  estudio_aleman_medico text not null,
  presento_fsp text not null,
  presento_kenntnis text not null,
  documentos jsonb not null default '{}'::jsonb,
  envio_documentos text not null,
  bundesland_envio text,
  recibio_respuesta text,
  solicitaron_examen text,
  tiene_berufserlaubnis text not null,
  tiene_approbation text not null,
  tipo_visa text not null,
  viaja_con_pareja text not null,
  pareja_habla_aleman text,
  nivel_aleman_pareja text,
  pareja_profesion text,
  dinero_ahorrado text not null,
  puede_abrir_sperrkonto text not null,
  apoyo_familiar text not null,
  dispuesto_ciudades_pequenas text not null,
  especialidad_interes text,
  dispuesto_especialidades jsonb default '[]'::jsonb,
  ha_aplicado_hospitales text not null,
  ha_tenido_entrevistas text not null,
  cuando_viajar text not null,
  puede_estudiar_intensivo text not null,
  puede_dedicar_1a2_horas text not null,
  motivacion text not null,
  score_idioma integer not null default 0,
  score_documentos integer not null default 0,
  score_homologacion integer not null default 0,
  score_finanzas integer not null default 0,
  score_estrategia integer not null default 0,
  score_total integer not null default 0,
  clasificacion text not null default 'Ruta preparatoria',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.diagnostico_submissions enable row level security;

create policy "Allow anonymous insert" on public.diagnostico_submissions
  for insert with check (true);

create policy "Allow authenticated read" on public.diagnostico_submissions
  for select using (true);
